services:
  gitea-server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=$USER_UID
      - USER_GID=$USER_GID
    restart: unless-stopped
    networks:
      - gitea
    env_file: .env  
    volumes:
      - $DATA_DIR:/data
      - $TIMEZONE:/etc/timezone:ro
      - $LOCALTIME:/etc/localtime:ro
    ports:
      - $ADMIN_PORT:3000
      - $SSH_PORT:22
networks:
  gitea:
    external: false