---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - $HOMEPAGE_VAR_HOST_PORT:$HOMEPAGE_VAR_CONTAINER_PORT
    volumes:
      - $HOMEPAGE_VAR_CONFIG_DIR:/app/config # Make sure your local config directory exists
      - $HOMEPAGE_VAR_ASSETS_DIR:/app/assets # Make sure your local assets directory exists
#      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    env_file: .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev, $HOMEPAGE_VAR_ALLOWED_HOST  # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts